language: python
python:
    - "2.7"
    - "pypy"

install:
    - pip install -r cyclone/tests/test_requirements.txt
    - pip install coveralls

script: coverage run `which trial` cyclone
after_success: coveralls
